language: python
python:
  - "3.5.3"
services:
  - docker
before_install:
 - sudo apt install opus-tools

install:
 - pip install -r requirements.txt
 - docker build https://github.com/stts-se/pronlex.git -t pronlex
 - docker run -v /tmp/appdir:/appdir -p 8787:8787 -t pronlex setup
 - docker run -v /tmp/appdir:/appdir -p 8787:8787 -t pronlex import_for_ws_test /appdir /tmp/appdir

before_script:
 - docker run -v /tmp/appdir:/appdir -p 8787:8787 -t pronlex & 
 - echo "pronlex server started with return value $?"
 - sleep 20
 - docker run -p 59125:59125 -t marytts & 
 - echo "marytts server started with return value $?"
 - sleep 20
  
# command to run tests
script:
  - python3 bin/wikispeech docker/config/travis.conf &
  - echo "wikispeech server started with return value $?"
  - sleep 20
  - ps -Af | egrep --color "pronlex"
  - ps -Af | egrep --color "wikispeech|python|pronlex|docker"
  - killall -9 python3 && killall -9 docker
  #- export pid=$! && sleep 10 && export ws_running=`ps -p $pid|egrep -vw PID|wc -l`
  #- echo 'if [ $ws_running -eq 1 ]; then kill -9 $pid ; else echo "Expected Wikispeech server to still be up and running after 10 seconds. Will exit with error code 1." && exit 1 ; fi' > /tmp/exit_right && sh /tmp/exit_right


