language: python
python:
  - "3.5.3"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - ls
  #- pytest # or py.test for Python versions 3.5 and below
  #- python3 bin/wikispeech 
