language: python
python:
  - "3.5.3"
services:
  - docker
before_install:
 - sudo apt install opus-tools
 - docker build https://github.com/stts-se/pronlex.git -t pronlex
 - docker run -v /tmp/appdir:/appdir -p 8787:8787 -it pronlex setup
 - docker run -v /tmp/appdir:/appdir -p 8787:8787 -it pronlex import_for_ws_test /appdir /tmp/appdir
 - docker run -v /tmp/appdir:/appdir -p 8787:8787 -it pronlex & 
 - sleep 20


install:
  - pip install -r requirements.txt

# command to run tests
script:
  - python3 bin/wikispeech docker/config/travis.conf &
  - sleep 20
  - ps -Af
  - killall -9 wikispeech && killall -9 pronlex
  #- export pid=$! && sleep 10 && export ws_running=`ps -p $pid|egrep -vw PID|wc -l`
  #- echo 'if [ $ws_running -eq 1 ]; then kill -9 $pid ; else echo "Expected Wikispeech server to still be up and running after 10 seconds. Will exit with error code 1." && exit 1 ; fi' > /tmp/exit_right && sh /tmp/exit_right


