version: '3'
#networks:
#  app_net:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#      - subnet: 172.99.0.0/16
services:
  pronlex:
    build: /home/hanna/go/src/github.com/stts-se/pronlex
    image: "pronlex"
    volumes:
     - /home/hanna/wikispeech/lexdata:/go/appdir
    ports:
     - "8787:8787"
    #networks:
    #  app_net:
    #    ipv4_address: 172.99.0.2
    #command: ifconfig
  marytts:
    build: /home/hanna/git_repos/wikispeech_mockup/docker/marytts
    image: "marytts"
    ports:
     - "59125:59125"
    #networks:
    #  app_net:
    #    ipv4_address: 172.99.0.3
    #command: ifconfig
  wikispeech:
    build: /home/hanna/git_repos/wikispeech_mockup/docker/wikispeech
    image: "wikispeech"
    volumes:
     - /home/hanna/git_repos/wikispeech_mockup/docker/ws-config:/ws-config
     - /home/hanna/git_repos/wikispeech_mockup/docker/compose/bin:/compose/bin
    ports:
     - "10000:10000"
    depends_on:
      - pronlex
      - marytts
    #networks:
    #  app_net:
    #    ipv4_address: 172.99.0.4
    command: ["/compose/bin/ws-postponed-start", "172.19.0.1:8787", "172.19.0.1:59125"]
